[package]
name = "RustGS"
version = "0.1.0"
authors = ["ug00031 <ug00031@surrey.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte = "0.2.4"
enum_primitive = "0.1.1"
dotenv = "*"
mysql="*"
bcrypt = "*"